---
- name: setup mac environment
  hosts: mylaptop
  connection: local

  sudo: false

  handlers:
    - name: unmount fuse filesystems
      shell: mount -t osxfusefs

    - name: unload fuse filesystems
      shell: kextunload -b com.github.osxfuse.filesystems.osxfusefs
      sudo: True
      ignore_errors: True

    - name: install osxfuse bundle
      shell: /bin/cp -RfX /usr/local/opt/osxfuse/Library/Filesystems/osxfusefs.fs /Library/Filesystems/
      sudo: True

    - name: chmod osxfuse bundle
      shell: chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs
      sudo: True

    - name: stowdir make
      shell: "cd ~/stowdir && make"

    - name: acme make
      shell: "cd ~/Projects/acme-tools && PREFIX=${HOME}/stowdir make"

    - name: writing tools make
      shell: "cd ~/Projects/writing-tools && PREFIX=${HOME}/stowdir make"

    - name: link bitlbee
      shell: "ln -sfv /usr/local/opt/bitlbee/*.plist ~/Library/LaunchAgents"

    - name: launch bitlbee
      shell: "launchctl load ~/Library/LaunchAgents/homebrew.mxcl.bitlbee.plist"

  tasks:

    - name: brew tap install
      homebrew_tap: tap="{{ item }}" state=present
      with_items:
          - "owncloud/owncloud"
          - "homebrew/completions"
          - "homebrew/binary"

    - name: newt install
      homebrew: name=newt state=latest update_homebrew=yes install_options=with-python
      tags:
        - install
        - homebrew

    - name: ensure ~/Library/Python/2.7/lib/python/site-packages directory
      file: path=~/Library/Python/2.7/lib/python/site-packages state=directory
      tags:
        - install
        - homebrew

    - name: ensure /Users/derekcarter/Library/Python/2.7/lib/python/site-packages/homebrew.pth exists
      file: path=~/Library/Python/2.7/lib/python/site-packages/homebrew.pth state=touch mode=0644
      tags:
        - install
        - homebrew

    - name: ensure ~/Library/Python/2.7/lib/python/site-packages/ paths are there
      lineinfile: dest=~/Library/Python/2.7/lib/python/site-packages/homebrew.pth line='/usr/local/lib/python2.7/site-packages' 
      tags:
        - install

    - name: weechat install
      homebrew: name=weechat state=latest update_homebrew=yes install_options=with-perl,with-python,with-ruby,with-lua
      tags:
        - install
        - weechat
        - homebrew

    - name: bitlbee install
      homebrew: name=bitlbee state=latest update_homebrew=yes install_options=with-libotr
      tags:
        - install
        - homebrew
        - bitlbee
      notify:
        - link bitlbee
        - launch bitlbee

    - name: brew install
      homebrew: name="{{ item }}" state=latest update_homebrew=yes
      with_items:
          - 'fswatch'
          #- 'git-flow'
          - bash
          - readline
          - byobu
          - git
          - binutils
          - cvs
          - imagemagick
          - rename
          - tmux
          - vim
          - sox
          - plan9port
          - ack
          - apg
          - asciidoc
          - aspell
          - packer
          - 'packer-completion'
          - 'bash-completion'
          - coreutils
          - elinks
          - wget
          - gpg-agent
          - keepassc
          - mtr
          - nmap
          - 'peg-markdown'
          - pyenv
          - 'pyenv-virtualenv'
          - 'pyenv-virtualenvwrapper'
          - 'rdiff-backup'
          - ssh-copy-id
          - stow
          - tree
          - z
          - iniparser
          # - qtkeychain # TODO broken
          - pandoc
          - qemu
          #- 'homebrew/completions/vagrant-completion' #broken
      tags:
        - install
        - homebrew

    - name: install osxfuse
      homebrew: name=osxfuse state=latest
      tags:
        - install
        - homebrew
      notify:
        #- unmount fuse filesystems # make better TODO
        - unload fuse filesystems
        - install osxfuse bundle
        - chmod osxfuse bundle

    - name: bootstrap brew cask
      shell: brew install caskroom/cask/brew-cask creates=/usr/local/Cellar/brew-cask/0.39.3
      sudo: true
      tags:
        - install
        - homebrew
        - bootstrap
        - cask

    - name: brew cask install
      homebrew_cask: name="{{ item }}" state=installed
      with_items:
          - atom
          - chromium
          - dia
          - divvy
          - "dropbox-encore"
          - dropbox
          - evernote
          - freemind
          - gimp
          # - gpgtools #discover if gpgtools is same as gpg suite
          # - handbrake # if personal
          # - handbrakebatch # if personal
          # - handbrakecli # if personal
          - inkscape
          - iterm2
          # - joinme # if personal
          - keepassx
          - 'komodo-edit'
          - 'lastpass-universal'
          #- minecraft # if personal
          - owncloud
          #- prey # TODO fix
          #- sickbeard # if personal
          - silverlight
          - sketchup
          - sketchupviewer
          # - snes9x # if personal
          - sshfs
          - xquartz
          - virtualbox
          - vagrant
          - vagrant-manager
      tags:
        - install
        - homebrew
        - cask

    - name: brew cask install
      homebrew_cask: name="gpgtools" state=installed
      sudo: yes
      tags:
        - install
        - homebrew
        - cask
        - gpg

    - name: pip install
      pip: name="{{item}}" state=latest
      sudo: yes
      with_items:
        - Flask
      tags:
        - install
        - pip

    - name: easy install
      easy_install: name="{{item}}"
      sudo: yes
      with_items:
        - six
        - stormssh
      tags:
        - install
        - easyinstall

    - name: "ensure /mnt directory"
      file: dest=/mnt state=directory owner=root group=wheel mode=1777
      sudo: True
      tags:
        - fuse

    - name: ensure some directories
      file: dest={{ item }} state=directory 
      with_items:
        - "~/Projects"
        - "~/stowdir"
        - "~/tmp"
      tags:
        - directories
        - homedir
        - bootstrap

    - name: checkout stowdir
      git: repo=https://github.com/goozbach/StowDir.git dest="~/stowdir"
      tags:
        - git
        - directories
        - stowdir
        - stow
      notify:
        - stowdir make

    - name: checkout acme tools
      git: repo=https://github.com/goozbach/acme-tools.git dest="~/Projects/acme-tools"
      tags:
        - git
        - directories
        - stow
        - 'acme-tools'
        - acme
      notify:
        - acme make

    - name: checkout writing tools
      git: repo=https://github.com/goozbach/weasel-words.git dest="~/Projects/writing-tools"
      tags:
        - git
        - directories
        - stow
        - 'writing-tools'
      notify:
        - writing tools make
